# Generated by Django 4.2.21 on 2025-05-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_rename_certificatntaionalite_inscription_certificatnationalite_and_more'),
    ]

    operations = [
    ]
